sample_count: 100
confidence_interval: 0.95
turnout_rate: 0.938714286
popular_vote:
  PAP: 0.6694729155552813
  WP: 0.14548533648546666
  PPP: 0.002870620828307803
  SUP: 0.0025448084228774453
  SPP: 0.011726876476151709
  PSP: 0.047410200692676784
  RDU: 0.039126904466132505
  PAR: 0.025868802984394076
  SDP: 0.03641031882243442
  SDA: 0.012502560105097864
  NSP: 0.0010090162349412775
  Independent: 0.005571638926238124
predicted_next_government: PAP
update_counter: 33
last_updated: 1757587806
constituencies:
- name: Aljunied GRC
  seats: 5
  polling_stations: 67
  registered_voters: 144276
  winner: WP
  spread: 0.022969357608403573
  parties:
  - name: PAP
    sample_count: 41
    confidence_interval:
    - 0.39851532119579824
    - 0.4214846788042017
  - name: WP
    sample_count: 59
    confidence_interval:
    - 0.5785153211957982
    - 0.6014846788042018
  update_seq: 33
- name: Ang Mo Kio GRC
  seats: 5
  polling_stations: 74
  registered_voters: 61494
  winner: PAP
  spread: 0.01734099005544798
  parties:
  - name: PAP
    sample_count: 79
    confidence_interval:
    - 0.781329504972276
    - 0.798670495027724
  - name: PPP
    sample_count: 10
    confidence_interval:
    - 0.09361380823792884
    - 0.10638619176207118
  - name: SUP
    sample_count: 11
    confidence_interval:
    - 0.1033394200392421
    - 0.1166605799607579
  update_seq: 1
- name: Bishan-Toa Payoh GRC
  seats: 4
  polling_stations: 48
  registered_voters: 98679
  winner: PAP
  spread: 0.02386252481941198
  parties:
  - name: PAP
    sample_count: 75
    confidence_interval:
    - 0.738068737590294
    - 0.761931262409706
  - name: SPP
    sample_count: 25
    confidence_interval:
    - 0.238068737590294
    - 0.261931262409706
  update_seq: 2
- name: Chua Chu Kang GRC
  seats: 4
  polling_stations: 41
  registered_voters: 93512
  winner: PAP
  spread: 0.028865023191555483
  parties:
  - name: PAP
    sample_count: 63
    confidence_interval:
    - 0.6155674884042223
    - 0.6444325115957777
  - name: PSP
    sample_count: 37
    confidence_interval:
    - 0.35556748840422225
    - 0.38443251159577774
  update_seq: 3
- name: East Coast GRC
  seats: 5
  polling_stations: 52
  registered_voters: 151024
  winner: PAP
  spread: 0.02624577376079673
  parties:
  - name: PAP
    sample_count: 59
    confidence_interval:
    - 0.5768771131196017
    - 0.6031228868803983
  - name: WP
    sample_count: 41
    confidence_interval:
    - 0.3968771131196016
    - 0.42312288688039834
  update_seq: 4
- name: Holland-Bukit Timah GRC
  seats: 4
  polling_stations: 54
  registered_voters: 123169
  winner: PAP
  spread: 0.02083801568691812
  parties:
  - name: PAP
    sample_count: 80
    confidence_interval:
    - 0.789580992156541
    - 0.8104190078434591
  - name: RDU
    sample_count: 20
    confidence_interval:
    - 0.18958099215654095
    - 0.21041900784345907
  update_seq: 5
- name: Jalan Besar GRC
  seats: 4
  polling_stations: 52
  registered_voters: 106327
  winner: PAP
  spread: 0.022923019496680824
  parties:
  - name: PAP
    sample_count: 75
    confidence_interval:
    - 0.7385384902516596
    - 0.7614615097483404
  - name: PAR
    sample_count: 25
    confidence_interval:
    - 0.2385384902516596
    - 0.2614615097483404
  update_seq: 6
- name: Jurong East-Bukit Batok GRC
  seats: 5
  polling_stations: 65
  registered_voters: 142728
  winner: PAP
  spread: 0.020260041087976077
  parties:
  - name: PAP
    sample_count: 76
    confidence_interval:
    - 0.749869979456012
    - 0.770130020543988
  - name: RDU
    sample_count: 24
    confidence_interval:
    - 0.22986997945601195
    - 0.25013002054398803
  update_seq: 7
- name: Marine Parade-Braddell Heights GRC
  seats: 5
  polling_stations: 62
  registered_voters: 131789
  winner: PAP
  spread: 0.0
  parties:
  - name: PAP
    sample_count: 100
    confidence_interval:
    - 1.0
    - 1.0
  update_seq: 8
- name: Marsiling-Yew Tee GRC
  seats: 4
  polling_stations: 56
  registered_voters: 119516
  winner: PAP
  spread: 0.022401457810183434
  parties:
  - name: PAP
    sample_count: 74
    confidence_interval:
    - 0.7287992710949083
    - 0.7512007289050917
  - name: SDP
    sample_count: 26
    confidence_interval:
    - 0.24879927109490835
    - 0.27120072890509167
  update_seq: 9
- name: Nee Soon GRC
  seats: 5
  polling_stations: 68
  registered_voters: 151836
  winner: PAP
  spread: 0.02035235389903245
  parties:
  - name: PAP
    sample_count: 74
    confidence_interval:
    - 0.7298238230504838
    - 0.7501761769495162
  - name: RDU
    sample_count: 26
    confidence_interval:
    - 0.2498238230504838
    - 0.27017617694951623
  update_seq: 10
- name: Pasir Ris-Changi GRC
  seats: 4
  polling_stations: 48
  registered_voters: 100706
  winner: PAP
  spread: 0.02592666290402279
  parties:
  - name: PAP
    sample_count: 67
    confidence_interval:
    - 0.6570366685479887
    - 0.6829633314520114
  - name: SDA
    sample_count: 33
    confidence_interval:
    - 0.3170366685479886
    - 0.3429633314520114
  update_seq: 11
- name: Punggol GRC
  seats: 4
  polling_stations: 53
  registered_voters: 123778
  winner: PAP
  spread: 0.026222676342667173
  parties:
  - name: PAP
    sample_count: 54
    confidence_interval:
    - 0.5268886618286664
    - 0.5531113381713336
  - name: WP
    sample_count: 46
    confidence_interval:
    - 0.44688866182866643
    - 0.4731113381713336
  update_seq: 12
- name: Sembawang GRC
  seats: 5
  polling_stations: 55
  registered_voters: 134103
  winner: PAP
  spread: 0.024310009324142623
  parties:
  - name: PAP
    sample_count: 67
    confidence_interval:
    - 0.6578449953379287
    - 0.6821550046620714
  - name: SDP
    sample_count: 31
    confidence_interval:
    - 0.2980445438539882
    - 0.3219554561460118
  - name: NSP
    sample_count: 2
    confidence_interval:
    - 0.01638099824143816
    - 0.023619001758561842
  update_seq: 13
- name: Sengkang GRC
  seats: 4
  polling_stations: 60
  registered_voters: 126808
  winner: WP
  spread: 0.024485079684940514
  parties:
  - name: WP
    sample_count: 56
    confidence_interval:
    - 0.5477574601575298
    - 0.5722425398424703
  - name: PAP
    sample_count: 44
    confidence_interval:
    - 0.4277574601575298
    - 0.4522425398424702
  update_seq: 14
- name: Tampines GRC
  seats: 5
  polling_stations: 64
  registered_voters: 148098
  winner: PAP
  spread: 0.02389136551181248
  parties:
  - name: PAP
    sample_count: 53
    confidence_interval:
    - 0.5180543172440938
    - 0.5419456827559063
  - name: WP
    sample_count: 46
    confidence_interval:
    - 0.4480711134318308
    - 0.4719288865681692
  - name: PPP
    sample_count: 1
    confidence_interval:
    - 0.0076185486687350154
    - 0.012381451331264986
  - name: NSP
    sample_count: 0
    confidence_interval:
    - 0.0
    - 0.0
  update_seq: 15
- name: Tanjong Pagar GRC
  seats: 5
  polling_stations: 61
  registered_voters: 140075
  winner: PAP
  spread: 0.019231728908678747
  parties:
  - name: PAP
    sample_count: 81
    confidence_interval:
    - 0.8003841355456607
    - 0.8196158644543394
  - name: PAR
    sample_count: 19
    confidence_interval:
    - 0.18038413554566066
    - 0.19961586445433935
  update_seq: 16
- name: West Coast-Jurong West GRC
  seats: 5
  polling_stations: 78
  registered_voters: 158817
  winner: PAP
  spread: 0.021080097690209576
  parties:
  - name: PAP
    sample_count: 61
    confidence_interval:
    - 0.5994599511548953
    - 0.6205400488451047
  - name: PSP
    sample_count: 39
    confidence_interval:
    - 0.3794599511548952
    - 0.4005400488451048
  update_seq: 17
- name: Bukit Gombak SMC
  seats: 1
  polling_stations: 11
  registered_voters: 26418
  winner: PAP
  spread: 0.05004107685398895
  parties:
  - name: PAP
    sample_count: 75
    confidence_interval:
    - 0.7249794615730055
    - 0.7750205384269945
  - name: PSP
    sample_count: 25
    confidence_interval:
    - 0.22497946157300552
    - 0.2750205384269945
  update_seq: 18
- name: Bukit Panjang SMC
  seats: 1
  polling_stations: 17
  registered_voters: 33594
  winner: PAP
  spread: 0.04489779002679184
  parties:
  - name: PAP
    sample_count: 62
    confidence_interval:
    - 0.5975511049866041
    - 0.6424488950133959
  - name: SDP
    sample_count: 38
    confidence_interval:
    - 0.3575511049866041
    - 0.4024488950133959
  update_seq: 19
- name: Hougang SMC
  seats: 1
  polling_stations: 13
  registered_voters: 29466
  winner: WP
  spread: 0.05125382054759309
  parties:
  - name: PAP
    sample_count: 37
    confidence_interval:
    - 0.34437308972620345
    - 0.39562691027379654
  - name: WP
    sample_count: 63
    confidence_interval:
    - 0.6043730897262035
    - 0.6556269102737965
  update_seq: 20
- name: Jalan Kayu SMC
  seats: 1
  polling_stations: 13
  registered_voters: 29620
  winner: Inconclusive
  spread: 0.053043564991542835
  parties:
  - name: PAP
    sample_count: 52
    confidence_interval:
    - 0.4934782175042286
    - 0.5465217824957714
  - name: WP
    sample_count: 48
    confidence_interval:
    - 0.45347821750422856
    - 0.5065217824957714
  update_seq: 21
- name: Jurong Central SMC
  seats: 1
  polling_stations: 14
  registered_voters: 29669
  winner: PAP
  spread: 0.0400629764539957
  parties:
  - name: PAP
    sample_count: 81
    confidence_interval:
    - 0.7899685117730022
    - 0.8300314882269979
  - name: RDU
    sample_count: 19
    confidence_interval:
    - 0.16996851177300218
    - 0.21003148822699783
  update_seq: 22
- name: Kebun Baru SMC
  seats: 1
  polling_stations: 11
  registered_voters: 22251
  winner: PAP
  spread: 0.05450790661413896
  parties:
  - name: PAP
    sample_count: 66
    confidence_interval:
    - 0.6327460466929306
    - 0.6872539533070695
  - name: PSP
    sample_count: 34
    confidence_interval:
    - 0.3127460466929306
    - 0.36725395330706945
  update_seq: 23
- name: Marymount SMC
  seats: 1
  polling_stations: 11
  registered_voters: 23264
  winner: PAP
  spread: 0.05227527525413411
  parties:
  - name: PAP
    sample_count: 71
    confidence_interval:
    - 0.683862362372933
    - 0.736137637627067
  - name: PSP
    sample_count: 29
    confidence_interval:
    - 0.2638623623729329
    - 0.31613763762706704
  update_seq: 24
- name: Mountbatten SMC
  seats: 1
  polling_stations: 9
  registered_voters: 22831
  winner: PAP
  spread: 0.06208975682320261
  parties:
  - name: PAP
    sample_count: 62
    confidence_interval:
    - 0.5889551215883987
    - 0.6510448784116013
  - name: Independent
    sample_count: 38
    confidence_interval:
    - 0.3489551215883987
    - 0.4110448784116013
  update_seq: 25
- name: Pioneer SMC
  seats: 1
  polling_stations: 12
  registered_voters: 25195
  winner: PAP
  spread: 0.05223988167348659
  parties:
  - name: PAP
    sample_count: 66
    confidence_interval:
    - 0.6338800591632567
    - 0.6861199408367433
  - name: PSP
    sample_count: 34
    confidence_interval:
    - 0.3138800591632568
    - 0.36611994083674326
  update_seq: 26
- name: Potong Pasir SMC
  seats: 1
  polling_stations: 13
  registered_voters: 30959
  winner: PAP
  spread: 0.04822745733458689
  parties:
  - name: PAP
    sample_count: 71
    confidence_interval:
    - 0.6858862713327065
    - 0.7341137286672934
  - name: SPP
    sample_count: 21
    confidence_interval:
    - 0.1883549103194461
    - 0.2316450896805539
  - name: PAR
    sample_count: 8
    confidence_interval:
    - 0.06558299318694888
    - 0.09441700681305112
  update_seq: 27
- name: Queenstown SMC
  seats: 1
  polling_stations: 14
  registered_voters: 28905
  winner: PAP
  spread: 0.03920722033352031
  parties:
  - name: PAP
    sample_count: 82
    confidence_interval:
    - 0.8003963898332398
    - 0.8396036101667601
  - name: PAR
    sample_count: 18
    confidence_interval:
    - 0.16039638983323984
    - 0.19960361016676015
  update_seq: 28
- name: Radin Mas SMC
  seats: 1
  polling_stations: 13
  registered_voters: 25559
  winner: PAP
  spread: 0.04891399896202797
  parties:
  - name: PAP
    sample_count: 69
    confidence_interval:
    - 0.665543000518986
    - 0.7144569994810139
  - name: Independent
    sample_count: 24
    confidence_interval:
    - 0.21741551461678724
    - 0.2625844853832128
  - name: PAR
    sample_count: 7
    confidence_interval:
    - 0.056507628942540036
    - 0.08349237105745998
  update_seq: 29
- name: Sembawang West SMC
  seats: 1
  polling_stations: 12
  registered_voters: 24192
  winner: PAP
  spread: 0.054979426886758054
  parties:
  - name: PAP
    sample_count: 53
    confidence_interval:
    - 0.502510286556621
    - 0.557489713443379
  - name: SDP
    sample_count: 47
    confidence_interval:
    - 0.44251028655662095
    - 0.497489713443379
  update_seq: 30
- name: Tampines Changkat SMC
  seats: 1
  polling_stations: 12
  registered_voters: 24032
  winner: PAP
  spread: 0.05479250308419781
  parties:
  - name: PAP
    sample_count: 55
    confidence_interval:
    - 0.5226037484579011
    - 0.577396251542099
  - name: WP
    sample_count: 45
    confidence_interval:
    - 0.42260374845790116
    - 0.47739625154209886
  update_seq: 31
- name: Yio Chu Kang SMC
  seats: 1
  polling_stations: 11
  registered_voters: 25404
  winner: PAP
  spread: 0.049310514795304794
  parties:
  - name: PAP
    sample_count: 76
    confidence_interval:
    - 0.7353447426023476
    - 0.7846552573976524
  - name: PAR
    sample_count: 24
    confidence_interval:
    - 0.2153447426023476
    - 0.2646552573976524
  update_seq: 32
